import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { ClerkProvider, UserButton } from '@clerk/nextjs';
import { ReactQueryProvider } from '@/client-providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ReactQueryProvider>
        <html lang='en'>
          <body className={inter.className}>
            <div className='flex flex-col mt-20 space-y-12 items-center'>
              <UserButton afterSignOutUrl='/' />
              {children}
            </div>
          </body>
        </html>
      </ReactQueryProvider>
    </ClerkProvider>
  );
}
